export const profile = {
  name: "Shaheer Shaikh",
  firstName: "Shaheer",
  role: "WordPress Developer & GHL Expert",
  tagline:
    "WordPress and Go HighLevel (GHL) specialist with over 3 years of experience in CRM development, sales automation, and lead generation. I build responsive websites and intelligent automation workflows — including AI agent–powered systems — that help businesses convert more leads and save time.",
  phone: "03313143864",
  phoneIntl: "+923313143864",
  whatsapp: "https://wa.me/923313143864",
  email: "shaheershaikh392@gmail.com",
  location: "Karachi, Pakistan",
  cv: "/Shaheer-CV.pdf",
  website: "www.shaheershaikh392.com",
  yearsExperience: "3+",
  projectsCompleted: "500+",
};

export const socials = [
  {
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/shaheer-shaikh-ghl-expert/",
    icon: "in",
  },
  {
    name: "Instagram",
    url: "https://www.instagram.com/shaheer4436/",
    icon: "ig",
  },
  {
    name: "Facebook",
    url: "https://www.facebook.com/shaheer.shaikh.537537",
    icon: "fb",
  },
];

export const skills = [
  { name: "WordPress", level: 95, icon: "/icons/wordpress.svg" },
  { name: "GoHighLevel", level: 92, icon: "/icons/ghl.png" },
  { name: "Funnel Building", level: 90, icon: "/icons/funnel.svg" },
  { name: "AI Agents", level: 85, icon: "/icons/ai.svg" },
  { name: "Shopify", level: 80, icon: "/icons/shopify.svg" },
  { name: "HTML 5", level: 90, icon: "/icons/html5.svg" },
  { name: "CSS 3", level: 88, icon: "/icons/css.svg" },
  { name: "JavaScript", level: 75, icon: "/icons/javascript.svg" },
];

export const experience = [
  {
    company: "D1TechCreative",
    logo: "/icons/d1tech.png",
    role: "Web Developer — WordPress & GHL Expert",
    period: "Dec 2025 — Present",
    description:
      "Building and managing websites while developing CRM automations and AI agent–driven workflows to streamline client operations and lead handling.",
    tools: ["WordPress", "Elementor", "GoHighLevel", "AI Agents", "Zapier", "Funnels", "SEO"],
  },
  {
    company: "Leadflex",
    logo: "/icons/leadflex.png",
    role: "WordPress Developer & GHL Expert",
    period: "Feb 2025 — Nov 2025",
    description:
      "Built responsive websites, custom funnels, and CRM automations that boosted conversions and improved digital presence.",
    tools: ["WordPress", "GoHighLevel", "Funnel Building", "CRM Automation", "Email/SMS"],
  },
  {
    company: "Hamsol",
    logo: "/icons/hamsol.png",
    role: "WordPress Developer & GHL Expert",
    period: "Mar 2025 — Dec 2025",
    description:
      "Built responsive, SEO-optimized websites with custom themes. Focused on improving speed, design, and functionality using HTML, CSS, PHP, and WordPress customization.",
    tools: ["WordPress", "HTML5", "CSS3", "PHP", "Speed Optimization", "SEO"],
  },
  {
    company: "Zg Tech Solutions",
    logo: "/icons/zgtech.png",
    role: "WordPress Developer & GHL Expert",
    period: "Feb 2023 — Dec 2024",
    description:
      "Developed websites, custom funnels, and CRM automations that improved lead generation for clients.",
    tools: ["WordPress", "Elementor", "GoHighLevel", "Lead Generation", "JavaScript"],
  },
];

export const achievements = [
  {
    title: "500+ Websites Launched",
    period: "2023 — Present",
    description:
      "Designed, built and launched over five hundred websites across WordPress, Shopify and GoHighLevel for clients in the US, UK, Australia, UAE and Pakistan.",
  },
  {
    title: "40+ GoHighLevel Funnels & CRM Systems",
    period: "2024 — Present",
    description:
      "Delivered complete GHL builds — pipelines, calendars, automations and AI agents — for agencies, real estate teams, healthcare and home-service businesses.",
  },
  {
    title: "Sub-2-Second Load Times",
    period: "Ongoing",
    description:
      "Speed-optimized dozens of WordPress sites from 4–8 second loads down to under 2 seconds, passing Core Web Vitals and improving search rankings.",
  },
  {
    title: "AI Agent Systems in Production",
    period: "2025 — Present",
    description:
      "Built AI-powered conversation agents that qualify leads, answer FAQs and book appointments 24/7 — running live inside client CRMs.",
  },
];

export const education = [
  {
    school: "Federal Urdu University of Karachi",
    logo: "/icons/fuuast.png",
    degree: "Bachelor of Science in Computer Information",
    period: "2025 — 2029 · Present",
  },
  {
    school: "Aptech",
    logo: "/icons/aptech.png",
    degree: "ACCP Prime 2.0",
    period: "2022 — 2025 · Completed",
  },
  {
    school: "Government Polytechnic Institute",
    logo: "/icons/gpi.png",
    degree: "Diploma of Associate Engineering (3 Years)",
    period: "2022 — 2025 · Completed",
  },
  {
    school: "Al Jawad Higher Secondary School",
    degree: "Intermediate",
    period: "2022 — 2024",
  },
  {
    school: "Wali Memorial Public School",
    degree: "Matriculation",
    period: "2010 — 2022",
  },
];

export const services = [
  {
    slug: "wordpress-development",
    title: "WordPress Development",
    short: "Fast, responsive, SEO-ready WordPress websites with custom themes.",
    description:
      "I design and develop custom WordPress websites that load fast, rank well, and convert visitors into customers. From landing pages to full business sites — custom themes, plugin configuration, speed optimization, and on-page SEO are all part of the package.",
    points: [
      "Custom theme design & development",
      "Speed & Core Web Vitals optimization",
      "SEO-friendly structure",
      "Responsive on every device",
      "Elementor / page-builder expertise",
    ],
  },
  {
    slug: "ghl-crm-automation",
    title: "GHL CRM & Automation",
    short: "Go HighLevel CRM setup, pipelines and sales automation that never sleeps.",
    description:
      "As a Go HighLevel expert, I build complete CRM systems: pipelines, calendars, SMS/email follow-up sequences, and automations that capture, nurture, and convert leads on autopilot — so your team can focus on closing.",
    points: [
      "Full GHL account setup & snapshots",
      "Sales pipelines & opportunity tracking",
      "Automated SMS / email follow-ups",
      "Appointment booking & reminders",
      "Reporting dashboards",
    ],
  },
  {
    slug: "funnel-building",
    title: "Funnel Building & Optimization",
    short: "High-converting sales funnels engineered to turn clicks into customers.",
    description:
      "I build and optimize sales funnels — landing pages, upsells, order forms, and thank-you flows — with tracking wired in, then iterate on copy and layout to increase conversion rates.",
    points: [
      "Landing page design",
      "A/B-ready funnel structures",
      "Upsell / downsell flows",
      "Conversion tracking & pixels",
      "Copy & layout optimization",
    ],
  },
  {
    slug: "ai-agents-workflows",
    title: "AI Agents & Workflows",
    short: "AI agent–powered systems that qualify leads and reply 24/7.",
    description:
      "I develop intelligent automation workflows powered by AI agents — conversation bots that qualify leads, book appointments, and answer FAQs around the clock, integrated directly into your CRM.",
    points: [
      "AI conversation bots for lead qualification",
      "24/7 automated responses",
      "Appointment-booking agents",
      "CRM-integrated workflows",
      "Custom automation logic",
    ],
  },
  {
    slug: "shopify",
    title: "Shopify Store Setup",
    short: "Clean, conversion-focused Shopify stores ready to sell.",
    description:
      "From theme customization to product setup, payments and apps — I build Shopify stores that look professional and are optimized to sell from day one.",
    points: [
      "Theme setup & customization",
      "Product & collection setup",
      "Payments & shipping configuration",
      "App integration",
      "Conversion-focused layout",
    ],
  },
  {
    slug: "lead-generation",
    title: "Lead Generation Systems",
    short: "End-to-end systems that capture, nurture and convert leads.",
    description:
      "Website + funnel + CRM + automation, working together as one machine. I connect every piece so no lead falls through the cracks — capture forms, instant follow-up, nurturing sequences, and clear reporting.",
    points: [
      "Lead capture forms & pop-ups",
      "Instant speed-to-lead follow-up",
      "Nurture sequences",
      "Pipeline visibility",
      "ROI reporting",
    ],
  },
];

export const pricing = [
  {
    platform: "WordPress",
    icon: "/icons/wordpress.svg",
    tagline:
      "Business websites, service sites and blogs — fast, SEO-ready and easy to manage.",
    plans: [
      {
        name: "Starter",
        price: 150,
        priceNote: "one-time",
        pages: "Up to 5 pages",
        summary:
          "Perfect for small businesses that need a clean, professional online presence.",
        features: [
          "Home, About, Services, Contact + 1 page",
          "Mobile-responsive design",
          "Contact form with email notifications",
          "Basic on-page SEO setup",
          "Google Maps & social links",
          "Speed-optimized setup",
        ],
        delivery: "5–7 days delivery",
      },
      {
        name: "Business",
        price: 300,
        priceNote: "one-time",
        pages: "Up to 10 pages",
        popular: true,
        summary:
          "The complete package for service businesses — like the sites in my portfolio.",
        features: [
          "Custom design (Elementor / custom theme)",
          "Service pages + blog setup",
          "Lead capture forms & pop-ups",
          "Speed & Core Web Vitals optimization",
          "On-page SEO for every page",
          "WhatsApp / live chat integration",
          "Google Analytics & Search Console",
        ],
        delivery: "7–14 days delivery",
      },
      {
        name: "Premium / WooCommerce",
        price: 600,
        priceNote: "starting at",
        pages: "15+ pages or full store",
        summary:
          "Large business sites or full online stores with WooCommerce.",
        features: [
          "Everything in Business",
          "WooCommerce store setup",
          "Up to 50 products added",
          "Payment gateway & shipping setup",
          "Advanced speed optimization",
          "Admin training video",
          "30 days post-launch support",
        ],
        delivery: "2–3 weeks delivery",
      },
    ],
  },
  {
    platform: "Shopify",
    icon: "/icons/shopify.svg",
    tagline:
      "Conversion-focused Shopify stores — set up properly and ready to sell from day one.",
    plans: [
      {
        name: "Basic Store",
        price: 250,
        priceNote: "one-time",
        pages: "Core store pages",
        summary:
          "A clean store on a free theme — ideal for launching your first products.",
        features: [
          "Theme setup & branding",
          "Up to 10 products added",
          "Home, About, Contact & policy pages",
          "Payment & shipping configuration",
          "Basic navigation & collections",
          "Mobile-ready checkout",
        ],
        delivery: "4–6 days delivery",
      },
      {
        name: "Standard Store",
        price: 450,
        priceNote: "one-time",
        pages: "Full store + custom sections",
        popular: true,
        summary:
          "Customized design and everything configured — the way stores like Milli Collections were built.",
        features: [
          "Premium theme customization",
          "Up to 50 products with collections",
          "Custom homepage sections",
          "Essential apps (reviews, upsell, email pop-up)",
          "Discount & shipping rules",
          "Basic email automation (abandoned cart)",
          "On-page SEO for products",
        ],
        delivery: "1–2 weeks delivery",
      },
      {
        name: "Premium Store",
        price: 800,
        priceNote: "starting at",
        pages: "Fully custom store",
        summary:
          "A fully custom, conversion-optimized store for serious brands.",
        features: [
          "Everything in Standard",
          "Custom design & landing pages",
          "Up to 200 products migrated/added",
          "Conversion rate optimization",
          "Advanced app stack & integrations",
          "Store training video",
          "30 days post-launch support",
        ],
        delivery: "2–3 weeks delivery",
      },
    ],
  },
  {
    platform: "GoHighLevel",
    icon: "/icons/ghl.png",
    tagline:
      "Websites, funnels and CRM automation inside GHL — built to capture and convert leads 24/7.",
    plans: [
      {
        name: "Funnel Build",
        price: 200,
        priceNote: "one-time",
        pages: "1 funnel · up to 3 steps",
        summary:
          "A high-converting funnel for your offer — landing page, form and thank-you flow.",
        features: [
          "Landing page + thank-you page",
          "Opt-in form or survey",
          "Email & SMS confirmation automation",
          "Calendar booking step (optional)",
          "Tracking pixels installed",
          "Mobile-optimized design",
        ],
        delivery: "3–5 days delivery",
      },
      {
        name: "Website + CRM Setup",
        price: 450,
        priceNote: "one-time",
        pages: "Up to 8 pages + CRM",
        popular: true,
        summary:
          "Full GHL website with pipelines and follow-up automation — my most-requested build.",
        features: [
          "Complete GHL website (up to 8 pages)",
          "Sales pipeline & opportunity stages",
          "Calendar & appointment booking",
          "Automated email/SMS follow-ups",
          "Missed-call text-back automation",
          "Lead forms wired into the CRM",
          "Reporting dashboard setup",
        ],
        delivery: "1–2 weeks delivery",
      },
      {
        name: "Complete Automation Suite",
        price: 900,
        priceNote: "starting at",
        pages: "Website + funnels + AI",
        summary:
          "The full machine: website, funnels, CRM and an AI agent working around the clock.",
        features: [
          "Everything in Website + CRM",
          "Sales funnel(s) for your offers",
          "AI agent for chat & lead qualification",
          "Advanced multi-step workflows",
          "Snapshot of the whole system",
          "Third-party integrations (Zapier etc.)",
          "30 days post-launch support",
        ],
        delivery: "2–4 weeks delivery",
      },
    ],
  },
];

export const projects = [
  {
    name: "D1 Tech Creative",
    url: "https://www.d1techcreative.com/",
    image: "/shots/d1techcreative.webp",
    category: "Agency",
    platform: "WordPress",
    description: "Digital agency website with modern design and lead-gen focus.",
  },
  {
    name: "The Clean Power Experts",
    url: "https://thecleanpowerexperts.com/",
    image: "/shots/thecleanpowerexperts.webp",
    category: "Solar / Energy",
    platform: "WordPress",
    description: "Solar energy company site built to capture and convert leads.",
  },
  {
    name: "GuaraBoost",
    url: "https://guaraboost.com/",
    image: "/shots/guaraboost.webp",
    category: "E-commerce",
    platform: "WordPress",
    description: "Product brand website with bold visuals and online sales flow.",
  },
  {
    name: "A Plus Moving & Storage",
    url: "https://aplusmovingandstorage.co/",
    image: "/shots/aplusmovingandstorage.webp",
    category: "Services",
    platform: "WordPress",
    description: "Moving company site with quote funnels and service pages.",
  },
  {
    name: "The Paper Roll",
    url: "https://thepaperroll.com/",
    image: "/shots/thepaperroll.webp",
    category: "E-commerce",
    platform: "WordPress",
    description: "B2B paper products store with catalog and ordering.",
  },
  {
    name: "Done By Dorfman",
    url: "https://www.donebydorfman.com",
    image: "/shots/donebydorfman.webp",
    category: "Personal Brand",
    platform: "WordPress",
    description: "Personal brand website with clean, professional presentation.",
  },
  {
    name: "Hamza Shakeel",
    url: "https://hamzashakeel.com/",
    image: "/shots/hamzashakeel.webp",
    category: "Personal Brand",
    platform: "WordPress",
    description: "Portfolio and personal brand site for a professional.",
  },
  {
    name: "Engr Sehtesham Hussain",
    url: "https://engrsehteshamhussain.com/",
    image: "/shots/engrsehteshamhussain.webp",
    category: "Personal Brand",
    platform: "WordPress",
    description: "Professional engineer's personal website and portfolio.",
  },
  {
    name: "Qulfi Wala",
    url: "https://qulfiwala.com/",
    image: "/shots/qulfiwala.webp",
    category: "Food Brand",
    platform: "WordPress",
    description: "Dessert brand website with menu and brand storytelling.",
  },
  {
    name: "Simplee Digital",
    url: "https://simplee.digital/",
    image: "/shots/simplee.webp",
    category: "Agency",
    platform: "WordPress",
    description: "Digital marketing agency site with service funnels.",
  },
  {
    name: "Everest Equipment Finance",
    url: "https://everestequipmentfinance.com/",
    image: "/shots/everestequipmentfinance.webp",
    category: "Finance",
    platform: "WordPress",
    description: "Equipment financing company with application funnels.",
  },
  {
    name: "Morse Junk Removal",
    url: "https://morsejunk.com/",
    image: "/shots/morsejunk.webp",
    category: "Services",
    platform: "WordPress",
    description: "Junk removal service site with booking and quote flows.",
  },
  {
    name: "Kyan Trading Services",
    url: "https://kyantradingservices.com/",
    image: "/shots/kyantradingservices.webp",
    category: "Trading",
    platform: "WordPress",
    description: "Trading and services company with corporate design.",
  },
  {
    name: "VitaHub",
    url: "https://vitahub.pk/",
    image: "/shots/vitahub.webp",
    category: "E-commerce",
    platform: "WordPress",
    description: "Health & wellness e-commerce store for Pakistan.",
  },
  {
    name: "Mary Angels Home Care",
    url: "https://www.maryangelshomecare.com/",
    image: "/shots/maryangelshomecare.webp",
    category: "Healthcare",
    platform: "WordPress",
    description: "Home care services website with warm, trustworthy design.",
  },
  {
    name: "Aligned Chiro",
    url: "https://alignedchiro.com.au/",
    image: "/shots/alignedchiro.webp",
    category: "Healthcare",
    platform: "Shopify",
    description: "Australian chiropractic clinic store built on Shopify.",
  },
  {
    name: "Milli Collections",
    url: "https://millicollections.com/",
    image: "/shots/millicollections.webp",
    category: "E-commerce",
    platform: "Shopify",
    description: "Fashion & lifestyle Shopify store with clean product showcase.",
  },
  {
    name: "Compelified",
    url: "https://www.compelified.com/",
    image: "/shots/compelified.webp",
    category: "E-commerce",
    platform: "Shopify",
    description: "Modern Shopify store with conversion-focused product pages.",
  },
  {
    name: "GHL Rockstar",
    url: "https://ghlrockstar.com/",
    image: "/shots/ghlrockstar.webp",
    category: "Agency",
    platform: "GoHighLevel",
    description: "GoHighLevel agency website with funnels and automation.",
  },
  {
    name: "Foreclosure Solutions USA",
    url: "https://foreclosuresolutionsusa.com/",
    image: "/shots/foreclosuresolutionsusa.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Real estate foreclosure help site with lead capture funnels.",
  },
  {
    name: "Liv Funding",
    url: "https://livfunding.com/",
    image: "/shots/livfunding.webp",
    category: "Finance",
    platform: "GoHighLevel",
    description: "Business funding website with application funnels.",
  },
  {
    name: "Soul Software",
    url: "https://soulsoftware.co/",
    image: "/shots/soulsoftware.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "Software company site built on GoHighLevel.",
  },
  {
    name: "Lewicki Team",
    url: "https://lewickiteam.com/",
    image: "/shots/lewickiteam.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Real estate team website with lead generation setup.",
  },
  {
    name: "Vanity Van Lines",
    url: "https://vanityvanlines.com/",
    image: "/shots/vanityvanlines.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Moving company website with quote request funnels.",
  },
  {
    name: "PW Hospital",
    url: "https://pwhospital.org/",
    image: "/shots/pwhospital.webp",
    category: "Healthcare",
    platform: "GoHighLevel",
    description: "Hospital website with appointment booking flows.",
  },
  {
    name: "Where2Print",
    url: "https://where2print.com/",
    image: "/shots/where2print.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Printing services website with order funnels.",
  },
  {
    name: "Top Local House Buyers",
    url: "https://toplocalhousebuyers.com/",
    image: "/shots/toplocalhousebuyers.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Cash home buying site with seller lead funnels.",
  },
  {
    name: "iPrograms",
    url: "https://iprograms.com/",
    image: "/shots/iprograms.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "Programs and software platform website.",
  },
  {
    name: "Impress Tech",
    url: "https://impresstech.com/",
    image: "/shots/impresstech.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "Technology company website built on GoHighLevel.",
  },
  {
    name: "Paw Works",
    url: "https://pawworks.org/",
    image: "/shots/pawworks.webp",
    category: "Nonprofit",
    platform: "GoHighLevel",
    description: "Animal rescue nonprofit website with donation flows.",
  },
  {
    name: "Valor House Buyers",
    url: "https://valorhousebuyers.com/",
    image: "/shots/valorhousebuyers.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Home buying company site with lead capture.",
  },
  {
    name: "Julie's Home Cleaning",
    url: "https://julieshomecleaning.com/",
    image: "/shots/julieshomecleaning.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Home cleaning services website with booking funnels.",
  },
  {
    name: "Immigration Law Firm",
    url: "https://app.gohighlevel.com/v2/preview/9VZiRF4mB7IYd5tt3F8I",
    image: "/shots/ghlpreview01.webp",
    category: "Legal",
    platform: "GoHighLevel",
    description: "Immigration & family law firm site with consultation booking.",
  },
  {
    name: "Philadelphia Basketball School",
    url: "https://app.gohighlevel.com/v2/preview/gXJSlzbBWKVgNbhROvOe",
    image: "/shots/ghlpreview02.webp",
    category: "Sports",
    platform: "GoHighLevel",
    description: "Youth sports program website with signup funnels.",
  },
  {
    name: "AW Loans",
    url: "https://app.gohighlevel.com/v2/preview/e5Be3MSbYxiPClLshP5p",
    image: "/shots/ghlpreview03.webp",
    category: "Finance",
    platform: "GoHighLevel",
    description: "Mortgage solutions website with quote request flows.",
  },
  {
    name: "HUBU Accountants",
    url: "https://app.gohighlevel.com/v2/preview/mEqt9FqyMcZLsKXxqXiF",
    image: "/shots/ghlpreview04.webp",
    category: "Finance",
    platform: "GoHighLevel",
    description: "Accounting firm site — taxation, bookkeeping and VAT services.",
  },
  {
    name: "VoiceAI HQ",
    url: "https://app.gohighlevel.com/v2/preview/YOuhR1vFnVCID3vC4AwN",
    image: "/shots/ghlpreview05.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "AI receptionist product site with demo and trial funnels.",
  },
  {
    name: "Clover Assist",
    url: "https://app.gohighlevel.com/v2/preview/NZQWwDRnoe5TQpWrak4M",
    image: "/shots/ghlpreview06.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "AI employee platform site that books meetings and closes leads.",
  },
  {
    name: "Sobha Hartland Apartments",
    url: "https://app.gohighlevel.com/v2/preview/7qdFoQ9lysbXF4BQ3Jyy",
    image: "/shots/ghlpreview07.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Dubai luxury apartments funnel with WhatsApp lead capture.",
  },
  {
    name: "FitPro PlayBook",
    url: "https://app.gohighlevel.com/v2/preview/xjasAdmNVUlGfJxeLRDP",
    image: "/shots/ghlpreview08.webp",
    category: "Coaching",
    platform: "GoHighLevel",
    description: "Fitness business coaching site with mentorship funnels.",
  },
  {
    name: "Lawnella Landscaping",
    url: "https://app.gohighlevel.com/v2/preview/gXxYJubnWi0QzwsSrWXc",
    image: "/shots/ghlpreview09.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Landscaping company site with residential & commercial services.",
  },
  {
    name: "Tube Mastery",
    url: "https://app.gohighlevel.com/v2/preview/Dqzrkrq119CHWXnqmvdj",
    image: "/shots/ghlpreview10.webp",
    category: "Coaching",
    platform: "GoHighLevel",
    description: "YouTube monetization course funnel with community signup.",
  },
  {
    name: "KillShot Auto Detailing",
    url: "https://app.gohighlevel.com/v2/preview/CzQenp1VcYGUwQujlSbZ",
    image: "/shots/ghlpreview11.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Luxury car detailing site with service tiers and booking.",
  },
  {
    name: "EdBridge",
    url: "https://app.gohighlevel.com/v2/preview/NShlaDO5vuPDqhJvRzFO",
    image: "/shots/ghlpreview12.webp",
    category: "Education",
    platform: "GoHighLevel",
    description: "Education platform site for in-demand digital skills.",
  },
  {
    name: "TradeAid",
    url: "https://app.gohighlevel.com/v2/preview/L89S1rj6jyKsYDgjuh1c",
    image: "/shots/ghlpreview13.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Construction professionals community with WhatsApp onboarding.",
  },
  {
    name: "Aligned Chiro Funnel",
    url: "https://app.gohighlevel.com/v2/preview/VOpquZUpoh0mxLAWhS0l?notrack=true",
    image: "/shots/ghlpreview14.webp",
    category: "Healthcare",
    platform: "GoHighLevel",
    description: "Chiropractic consultation offer funnel with pain assessment.",
  },
];

export const testimonials = [
  {
    name: "Daniel R.",
    role: "Founder — D1 Tech Creative",
    text: "Shaheer is our go-to developer for WordPress and GHL. Fast, reliable, and he genuinely cares about conversions — every site he touches performs better.",
  },
  {
    name: "Michael T.",
    role: "The Clean Power Experts",
    text: "Our solar site went from slow and clunky to fast and lead-generating. The forms, the funnels, the follow-up automation — everything just works.",
  },
  {
    name: "Gavin M.",
    role: "Morse Hauling & Junk Removal",
    text: "The new website brings us real calls every week. Free estimate form, reviews, service areas — Shaheer set the whole machine up perfectly.",
  },
  {
    name: "Sarah K.",
    role: "Mary Angels Home Care",
    text: "Professional, patient and quick. He understood exactly the warm, trustworthy feel we needed for our home care brand.",
  },
  {
    name: "Imran M.",
    role: "Qulfi Wala",
    text: "Hamari brand website ne business hi badal diya. Design bhi zabardast, speed bhi — aur order flow bilkul asaan.",
  },
  {
    name: "Ali H.",
    role: "VitaHub Pakistan",
    text: "From product pages to checkout, the store is clean and fast. Sales improved within the first month of launch.",
  },
  {
    name: "James L.",
    role: "Everest Equipment Finance",
    text: "The application funnels Shaheer built qualify leads before they ever reach our team. Massive time saver.",
  },
  {
    name: "Hamza S.",
    role: "hamzashakeel.com",
    text: "My personal brand site looks world-class. Smooth animations, quick load, and it actually gets me client inquiries.",
  },
];

export const blogPosts = [
  {
    slug: "gohighlevel-vs-traditional-crm",
    title: "GoHighLevel vs a Traditional CRM: Why Service Businesses Are Switching",
    date: "2026-07-21",
    readTime: "7 min read",
    cover: "/blog/ghl-vs-crm.svg",
    tags: ["GoHighLevel", "CRM", "Automation", "Small Business"],
    excerpt:
      "A traditional CRM stores contacts. GoHighLevel runs the whole growth engine. Here is the honest difference — and when it actually matters for your business.",
    content: [
      "Most service businesses do not have a CRM problem — they have a follow-up problem. Leads come in from ads, referrals and Google, then slowly leak out because nobody responds fast enough or follows up long enough. A traditional CRM was built to store contacts and log activity. GoHighLevel was built to actually move leads toward a sale, automatically. That is the real difference, and it is why so many agencies and local businesses have switched.",
      "## What a traditional CRM does well",
      "Classic CRMs like the big enterprise names are excellent at organising large sales teams: contact records, deal stages, reporting and permissions. If you have 20 salespeople and a complex pipeline, they shine. But for a plumber, a clinic, a coach or a small agency, that power comes with a cost — you still need to bolt on a separate email tool, an SMS tool, a booking calendar, a funnel builder and a way to tie them all together. Each one is another subscription and another integration that can break.",
      "## What GoHighLevel does differently",
      "GHL bundles the whole stack into one place: CRM, two-way SMS and email, a calendar, funnel and website builder, review requests, and automation workflows that connect it all. When a lead fills a form, GHL can text them in seconds, notify you, add them to a follow-up sequence and drop them into the right pipeline stage — with no human touching a keyboard. For a small team, replacing five tools with one that talks to itself is a genuine unlock.",
      "## The speed-to-lead advantage",
      "The single biggest reason businesses switch is speed-to-lead. Responding within five minutes makes you many times more likely to win the customer than responding an hour later. A traditional CRM will remind you to follow up; GHL does the follow-up for you, instantly, at any hour. That is the gap between a system that records what happened and a system that makes things happen.",
      "## So which should you choose?",
      "If you are a large sales organisation with a dedicated ops team, a traditional CRM may fit best. If you are a service business or agency that lives and dies by fast follow-up and wants marketing, booking and CRM in one roof, GoHighLevel is usually the better and cheaper answer. I set these systems up end to end — if you want to see whether GHL fits your business, send me the details and I will give you an honest recommendation.",
    ],
  },
  {
    slug: "local-seo-for-service-businesses",
    title: "Local SEO: How to Show Up When Nearby Customers Search",
    date: "2026-07-18",
    readTime: "8 min read",
    cover: "/blog/local-seo.svg",
    tags: ["SEO", "Local SEO", "WordPress", "Lead Generation"],
    excerpt:
      "Ranking in your city is a different game than ranking nationally. Here is the practical local SEO playbook I use to get service businesses found on Google and Maps.",
    content: [
      "When someone searches plumber near me or dentist in my city, Google shows a very different result than a national search — a map, three highlighted businesses, and reviews. Getting into that map pack is where local businesses win or lose. The good news: local SEO is far more winnable than competing nationally, because your competition is only the businesses in your area, not the entire internet.",
      "## Start with your Google Business Profile",
      "Your Google Business Profile is the single most important local ranking factor and it is free. Fill in every field: correct name, address and phone, categories, service areas, hours, photos and a real description. Keep it consistent with your website exactly — even small differences in how your address is written can hurt. Then ask happy customers for reviews, respond to every one, and post updates regularly. Reviews and activity are what push you up the map pack.",
      "## Make your website say where you work",
      "Google needs obvious signals about where you operate. Put your city and service areas in your page titles, headings and content — naturally, not stuffed. Create a dedicated page for each main service and, if you serve multiple areas, a page for each location. A page titled Emergency Plumbing in [City] will always beat a generic Services page for local searches.",
      "## Technical basics that quietly matter",
      "Speed and mobile experience are ranking signals, and most local searches happen on phones. A fast, mobile-friendly site with clear contact buttons converts the visitor and pleases Google at the same time. Add local business schema so search engines understand your name, address, phone and hours. Make sure your business appears consistently across directories — the same name, address and phone everywhere builds trust.",
      "## Reviews and content are the long game",
      "Steady reviews and helpful content compound over time. A simple blog answering the questions your customers actually ask — how much does X cost, how long does Y take — brings in searchers and positions you as the expert. Local SEO is not a one-time task; it is a habit. But it is one of the highest-ROI marketing channels a local business has, because the people finding you are already looking to buy.",
    ],
  },
  {
    slug: "high-converting-landing-pages",
    title: "7 Elements Every High-Converting Landing Page Needs",
    date: "2026-07-15",
    readTime: "7 min read",
    cover: "/blog/landing-pages.svg",
    tags: ["Funnels", "Landing Pages", "Conversion", "Copywriting"],
    excerpt:
      "A landing page has one job: get the visitor to take one action. Here are the seven elements I include on every page that consistently convert.",
    content: [
      "A landing page is not a website. A website tells your whole story; a landing page has exactly one job — get the visitor to take a single action. Every element either moves them toward that action or gets in the way. After building funnels across dozens of industries, these are the seven elements I include on every high-converting page.",
      "## 1. A headline that speaks to one outcome",
      "The headline is 80% of the battle. It should promise one clear, specific outcome the visitor wants — not describe your company. Save more, book faster, get more leads. If a stranger cannot understand what they get within three seconds of landing, they leave.",
      "## 2. One offer, zero distractions",
      "Remove the full navigation menu. A landing page should not let people wander off to your blog or about page. One offer, one message, one path. This single change routinely lifts conversion rates because it eliminates every exit that is not the button you want them to click.",
      "## 3. Proof they can trust",
      "People believe other people more than they believe you. Reviews, testimonials, logos of clients, before-and-after results, star ratings, real numbers — place proof right where doubt creeps in, next to the price and the button. Trust is what turns interest into action.",
      "## 4. A clear, repeated call to action",
      "Tell them exactly what to do and repeat it. The same button — Book a free call, Get my quote — should appear near the top, in the middle and at the end. Make it a color that stands out. Never make a visitor hunt for how to say yes.",
      "## 5. Benefits, not features",
      "List what the visitor gets, not what you do. Not 24/7 automated system but never miss a lead again, even at midnight. People buy outcomes and feelings, then justify with features. Lead with the outcome.",
      "## 6. Handle the obvious objection",
      "Every offer triggers a doubt: is it expensive, is it hard, will it work for me. Answer it on the page — a guarantee, a no-obligation note, a quick FAQ. Removing the reason to hesitate removes the friction to convert.",
      "## 7. Built for mobile and speed",
      "Most traffic is on a phone, and a slow page loses conversions with every second. The page must load fast, read cleanly on a small screen, and put the button within thumb reach. Get these seven right and the same ad spend brings you noticeably more leads — that is the whole point of a funnel.",
    ],
  },
  {
    slug: "turn-visitors-into-leads",
    title: "How to Turn Website Visitors Into Leads (Even the Ones Not Ready to Buy)",
    date: "2026-07-11",
    readTime: "6 min read",
    cover: "/blog/capture-leads.svg",
    tags: ["Lead Generation", "Conversion", "Email", "Strategy"],
    excerpt:
      "Most of your visitors leave and never come back. Here is how to capture them, nurture the not-yet-ready ones, and turn traffic into a pipeline.",
    content: [
      "Here is an uncomfortable truth: the vast majority of people who visit your website will never contact you on that first visit — and if you do nothing, most are gone forever. They were curious, not ready. The businesses that win are the ones that capture those visitors and stay in touch until the timing is right. That is the difference between a website that looks nice and a website that generates leads.",
      "## Give them a reason to raise their hand",
      "Not everyone is ready to book a call, but many will trade their email for something useful — a free guide, a checklist, a quote, a discount, a quick assessment. This lead magnet turns an anonymous visitor into a known contact you can follow up with. The offer just has to be genuinely valuable and instantly relevant to what they came for.",
      "## Make capturing details effortless",
      "Every extra form field costs you leads. Ask for the minimum — often just a name and email or phone. Use clear, benefit-led buttons (Get my free quote, not Submit). Add a simple chat widget or WhatsApp button so people can reach out in the way that feels easiest to them. Reduce every point of friction between interest and contact.",
      "## Follow up automatically — this is where the money is",
      "Capturing the lead is step one; the follow-up is where deals are made. A short automated email or SMS sequence keeps you in front of the not-yet-ready buyer with helpful content and gentle nudges, so when they are ready, you are the obvious choice. The average buyer needs several touches before acting — automation makes sure every one of those touches actually happens.",
      "## Bring visitors back",
      "Some will slip away no matter what. Retargeting ads and a simple newsletter quietly pull them back to your site. Combined with capture and follow-up, you build a real pipeline instead of hoping every visitor buys on the spot. If your site gets traffic but few inquiries, this system is almost always the missing piece — and it is exactly the kind of setup I build for clients.",
    ],
  },
  {
    slug: "whatsapp-automation-for-business",
    title: "WhatsApp Automation for Business: Never Miss Another Lead",
    date: "2026-07-09",
    readTime: "6 min read",
    cover: "/blog/whatsapp-automation.svg",
    tags: ["Automation", "WhatsApp", "GoHighLevel", "Lead Response"],
    excerpt:
      "Your customers already live on WhatsApp. Here is how to automate replies, capture leads and book appointments right inside the app they check most.",
    content: [
      "In much of the world, WhatsApp is not a marketing channel — it is where business actually happens. Customers would rather message than fill a form or wait on a call. The problem is that you cannot sit in the app all day, and a lead who waits an hour for a reply often books with someone faster. WhatsApp automation solves exactly that.",
      "## Instant replies, day or night",
      "An automated WhatsApp assistant can greet every new message in seconds, answer common questions — do you serve my area, how much does it cost, what are your hours — and collect the details you need to help. The customer feels looked after immediately, even at midnight, and you wake up to qualified conversations instead of missed ones.",
      "## From chat to booked appointment",
      "The real power is connecting WhatsApp to your CRM. When someone messages, they are added as a lead, tagged by what they want, and can be booked straight into your calendar through the chat. No copying numbers into a spreadsheet, no leads forgotten in an inbox. The whole journey from first message to confirmed appointment happens in one thread.",
      "## Follow-up that does not feel like spam",
      "Automation also handles the gentle follow-ups people forget to send: a reminder before an appointment, a check-in on a quote, a thank-you after a job with a review request. Done well, it feels personal and timely — because it is triggered by what the customer actually did, not blasted to a list.",
      "## Keep it human where it counts",
      "The goal is not to replace real conversation — it is to handle the repetitive first steps instantly so you can step in for the moments that matter. A good setup knows when to hand off to a human. Built right, WhatsApp automation means every lead gets an instant, helpful response and nothing slips through the cracks. If your business gets messages you cannot always answer in time, this is the fix.",
    ],
  },
  {
    slug: "website-conversion-audit",
    title: "Website Conversion Audit: 10 Quick Wins to Get More Leads This Month",
    date: "2026-07-06",
    readTime: "8 min read",
    cover: "/blog/conversion-audit.svg",
    tags: ["Conversion", "Website", "Optimization", "Checklist"],
    excerpt:
      "You do not always need more traffic — often you need your current traffic to convert better. Here are 10 fixes that move the needle fast.",
    content: [
      "Before you spend more on ads, ask a cheaper question: is your website turning the visitors you already have into leads? Most sites leak conversions in small, fixable ways. Here are ten quick wins I check on every audit — each one can lift your inquiries without a single extra visitor.",
      "## 1. Make your call to action obvious",
      "Your main action — call, book, quote — should be visible the moment the page loads and repeated down the page in a color that stands out. If visitors have to hunt for how to contact you, most will not bother.",
      "## 2. Put contact info where thumbs are",
      "On mobile, a tap-to-call button and a WhatsApp link in easy reach can lift conversions immediately. People decide fast; make saying yes effortless.",
      "## 3. Fix your load speed",
      "Every extra second of load time loses visitors before they see anything. Compress images, enable caching, cut heavy plugins. Speed is both a conversion and an SEO win.",
      "## 4. Lead with the outcome, not your logo",
      "Your headline should say what the visitor gets, not just your business name. Clarity beats cleverness every time.",
      "## 5. Add real proof",
      "Reviews, testimonials, results and recognisable logos near your offer build the trust that turns interest into action. Borrowed credibility works.",
      "## 6. Shorten your forms",
      "Every unnecessary field costs leads. Ask only for what you truly need to start the conversation — you can gather the rest later.",
      "## 7. Answer the top objection",
      "Whatever makes people hesitate — price, effort, risk — address it directly with a guarantee, an FAQ or a reassuring line. Remove the reason to stall.",
      "## 8. Guide the eye down one path",
      "Reduce clutter and competing links on key pages so there is one clear next step. A focused page converts better than a busy one.",
      "## 9. Make it flawless on mobile",
      "Most of your traffic is on a phone. Test every page on a real device — readable text, tappable buttons, no sideways scrolling.",
      "## 10. Track what is happening",
      "Install analytics and, if you run ads, the right pixels. You cannot improve what you cannot see, and you cannot retarget visitors you never tracked. Work through this list and most businesses see more inquiries within weeks — from the exact same traffic.",
    ],
  },
  {
    slug: "wordpress-vs-shopify-vs-gohighlevel",
    title: "WordPress vs Shopify vs GoHighLevel: Which Platform Is Right for You?",
    date: "2026-06-24",
    readTime: "8 min read",
    cover: "/blog/platform-choice.svg",
    tags: ["WordPress", "Shopify", "GoHighLevel", "Strategy"],
    excerpt:
      "Picking the wrong platform means rebuilding later. Here is a plain-English guide to which one fits your business goal — from someone who builds on all three.",
    content: [
      "One of the first questions clients ask me is simply: what should my site be built on? It matters, because switching platforms later is expensive and painful. The honest answer is that there is no best platform — only the best fit for your goal. Here is how I decide between the three I build on most: WordPress, Shopify and GoHighLevel.",
      "## Choose WordPress for content and flexibility",
      "WordPress powers a huge share of the web for good reason: it can become almost anything — a service business site, a blog, a portfolio, a booking site, a directory. If you want full control over design, strong SEO, and a site you can grow in any direction over years, WordPress is the workhorse. It is my default for service businesses and brands that plan to publish content and rank on Google.",
      "## Choose Shopify to sell products",
      "If your core business is selling physical or digital products, Shopify is purpose-built for it — inventory, payments, shipping, taxes and checkout are all handled and secure out of the box. You could force an online store onto other platforms, but Shopify removes the headaches and scales cleanly as your catalog and orders grow. For a serious e-commerce brand, it is usually the right call.",
      "## Choose GoHighLevel to capture and convert leads",
      "GoHighLevel is less a website builder and more a growth machine. If your priority is generating leads and following up — funnels, CRM, SMS and email automation, booking, review requests, all in one place — GHL is built exactly for that. It is ideal for agencies, coaches and service businesses that run ads and need every lead responded to instantly and nurtured automatically.",
      "## Often the answer is a combination",
      "These are not mutually exclusive. A common setup is a WordPress site for authority and SEO, with GoHighLevel powering the funnels, CRM and automation behind it — and Shopify added if there is a product to sell. The right architecture depends on where your growth actually comes from. If you are unsure, tell me your goal and I will recommend the simplest setup that gets you there without over-building.",
    ],
  },
  {
    slug: "email-sms-follow-up-sequences",
    title: "Email and SMS Follow-Up: The Money Is in the Sequence",
    date: "2026-06-12",
    readTime: "7 min read",
    cover: "/blog/follow-up-sequence.svg",
    tags: ["Automation", "Email", "SMS", "GoHighLevel"],
    excerpt:
      "Most sales happen after the fifth follow-up, but most businesses quit after one. Here is how to build sequences that follow up for you — without being annoying.",
    content: [
      "A lead rarely buys the first time they hear from you. Studies consistently show most sales happen somewhere between the fifth and twelfth touch — yet most businesses follow up once or twice and give up. That gap is not a motivation problem; it is a systems problem. Automated follow-up sequences close it by making sure every lead gets nurtured, every time, without you remembering to.",
      "## Why the sequence beats the single message",
      "A single follow-up catches only the people ready to buy right now. A sequence stays in front of the many more who were interested but busy, distracted or not quite ready. Spacing helpful, relevant messages over days and weeks means you are still there when their timing finally lines up — and by then you feel familiar and trustworthy, not like a stranger.",
      "## What a good sequence looks like",
      "It is not the same sales pitch sent ten times. A strong sequence mixes value and offers: a quick thank-you and what to expect, then a helpful tip or answer to a common question, a piece of proof like a testimonial or result, a gentle nudge toward the next step, and the occasional direct offer. Each message earns the right to the next. SMS handles the urgent, time-sensitive touches; email carries the story and detail.",
      "## Let behavior trigger the messages",
      "The best sequences react to what the lead does. Opened but did not reply? Send a different angle. Clicked the pricing link? Follow up with a case study. Booked? Stop selling and start onboarding. This behavior-based branching is exactly what tools like GoHighLevel make possible, and it is what makes automation feel personal instead of robotic.",
      "## Know when to stop",
      "Good automation is polite. It stops the moment someone replies, books or unsubscribes, and it never blasts irrelevant messages to everyone. Done right, follow-up sequences quietly become one of the most profitable things in your business — reviving old leads, converting the undecided, and making sure no opportunity dies from silence. If you are collecting leads but not following up consistently, this is the highest-ROI system you can add.",
    ],
  },
  {
    slug: "ai-chatbot-vs-live-chat",
    title: "AI Chatbot vs Live Chat: Which One Should Your Business Use?",
    date: "2026-05-28",
    readTime: "6 min read",
    cover: "/blog/chatbot-vs-livechat.svg",
    tags: ["AI Agents", "Chatbots", "Customer Support", "Automation"],
    excerpt:
      "Both put a chat bubble on your site, but they solve different problems. Here is how to choose — and why the best answer is often both together.",
    content: [
      "You have seen the little chat bubble on business websites. Behind it is either a human on live chat or an AI chatbot — and they are not the same thing. Picking the right one, or combining them well, can be the difference between capturing a lead at 11pm and losing it. Here is the honest comparison.",
      "## Where live chat wins",
      "Live chat means a real person answering in real time. It is unbeatable for nuance — complex questions, sensitive situations, high-value deals where a human touch closes the sale. The catch is obvious: humans need to sleep, take breaks and cannot be in two chats at once. Outside working hours, live chat is just an unanswered box, and a slow reply can feel worse than no chat at all.",
      "## Where an AI chatbot wins",
      "A modern AI chatbot answers instantly, 24/7, and never gets tired or overwhelmed. It handles the repetitive questions that make up most conversations — services, pricing ranges, hours, areas covered — qualifies the lead, and can book appointments or hand off details to your team. It scales infinitely: ten visitors at midnight all get an immediate, helpful reply. Today's AI is genuinely good at natural conversation, so it rarely feels like the clunky bots of a few years ago.",
      "## The trade-off to be honest about",
      "A chatbot is only as good as its setup. Configured well — trained on your services, tone and rules, with clear handoff points — it feels like a helpful team member. Configured lazily, it frustrates people. The skill is not installing a widget; it is designing what it knows, what it must never promise, and exactly when to pass the conversation to a human.",
      "## The best answer: both, working together",
      "For most businesses the winning setup is a well-built AI agent as the front line — instant, always on, capturing and qualifying every visitor — with a smooth handoff to a real person for the moments that need one. You get the speed and coverage of automation and the warmth of a human where it counts. That is exactly the kind of AI assistant I build into client sites — like the one you can talk to right here.",
    ],
  },
  {
    slug: "cost-of-a-cheap-website",
    title: "The Real Cost of a Cheap Website (And Why It Is Never Actually Cheap)",
    date: "2026-05-15",
    readTime: "6 min read",
    cover: "/blog/cheap-website.svg",
    tags: ["WordPress", "Business", "Web Design", "Strategy"],
    excerpt:
      "A bargain website often becomes the most expensive thing a business buys. Here is what the low price really costs — and how to invest wisely instead.",
    content: [
      "Everyone loves a bargain, and a rock-bottom website quote is tempting when you are starting out. But over the years I have rebuilt many cheap websites, and the pattern is always the same: the low price up front turns into a much bigger cost down the road. A website is not an expense to minimise — it is your hardest-working salesperson. Here is what cheap really costs.",
      "## The cost of lost leads",
      "The most expensive part of a bad website is the customers you never even know you lost. A slow, confusing or untrustworthy site quietly turns visitors away before they ever contact you. If a poor site converts even a couple of percent worse than a good one, the leads lost every month can dwarf whatever you saved on the build — many times over, forever.",
      "## The cost of doing it twice",
      "Cheap sites are often built on shaky foundations — bloated templates, no strategy, no room to grow. Within a year or two you outgrow it or it starts breaking, and you pay again for a proper rebuild. Paying twice is always more expensive than paying once for something built to last. The bargain becomes the priciest option available.",
      "## The hidden costs: speed, SEO and security",
      "A cheap build usually skips the invisible essentials. It loads slowly, so it ranks lower on Google and loses impatient visitors. It is rarely optimised for search, so you stay invisible and end up paying for ads to make up for it. And it is often left unmaintained, making it a target — a hacked site or extended downtime can cost far more than the original build in lost trust and emergency fixes.",
      "## Invest, do not just spend",
      "None of this means expensive equals good, or that you should overpay. It means judge a website by return, not sticker price. A well-built site that loads fast, ranks, earns trust and converts pays for itself many times over. A cheap one costs you quietly every single day. Spend wisely on the thing that brings you customers — and if you are weighing a quote, I am happy to give you an honest opinion on what is worth paying for.",
    ],
  },
  {
    slug: "why-website-speed-matters",
    title: "Why Website Speed Matters (And How I Make WordPress Fly)",
    date: "2026-06-15",
    readTime: "7 min read",
    cover: "/blog/speed.svg",
    tags: ["WordPress", "Speed", "Core Web Vitals", "SEO"],
    excerpt:
      "A slow website silently kills your conversions. Here's the exact process I use to make WordPress sites load in under 2 seconds.",
    content: [
      "Every extra second your website takes to load, you lose visitors — studies consistently show that bounce rates jump dramatically after the 3-second mark. Google's own research found that as page load time goes from 1 second to 3 seconds, the probability of a bounce increases by 32%. At 5 seconds, it jumps to 90%. For a business website, speed isn't a technical detail. It's revenue.",
      "## The real cost of a slow website",
      "Imagine 1,000 people visit your site this month from ads, Google and social media. If your site takes 6 seconds to load, roughly half of them leave before seeing anything. That's 500 potential customers gone — not because your offer was bad, but because a spinner was still turning. I've seen service businesses double their lead volume without changing a single word of copy, purely by fixing load time.",
      "## Where WordPress sites lose their speed",
      "When I take on a speed project, I start with a full audit: which plugins load scripts on every page, how large the images are, whether the hosting is up to the job, and what the Core Web Vitals report says. Most slow sites share the same three problems — bloated page builders loading 2MB of JavaScript, unoptimized 4000-pixel images uploaded straight from a phone, and no caching strategy at all.",
      "The plugin problem is the sneakiest. A site accumulates plugins over the years — a slider here, a form there, three different SEO tools — and each one adds its own CSS and JavaScript to every single page. Twenty active plugins can easily mean sixty extra HTTP requests before your content even appears.",
      "## My optimization process",
      "My process covers image compression and WebP conversion, lazy loading below the fold, full-page caching plus browser and object cache, removing unused CSS and JavaScript per page, database cleanup, and choosing lightweight alternatives to heavy plugins. Where the hosting is the bottleneck, I move clients to servers with LiteSpeed or NGINX and PHP 8+. On most projects this takes a site from a 4–8 second load down to under 2 seconds.",
      "I always measure before and after with the same tools — PageSpeed Insights, GTmetrix and real-device testing on 4G — so the improvement is documented, not just 'it feels faster'.",
      "## What you get from a fast site",
      "The result isn't just a better PageSpeed score. Faster sites rank higher on Google (Core Web Vitals are a confirmed ranking signal), convert better, and feel more trustworthy to visitors. If your site feels slow, it's costing you leads every single day — and it's almost always fixable within a week.",
    ],
  },
  {
    slug: "ghl-automation-guide",
    title: "How GHL Automation Turns Missed Calls Into Booked Appointments",
    date: "2026-05-20",
    readTime: "8 min read",
    cover: "/blog/ghl.svg",
    tags: ["GoHighLevel", "Automation", "CRM", "Speed-to-Lead"],
    excerpt:
      "Speed-to-lead is everything. Here's how I build Go HighLevel automations that respond to every lead in under 60 seconds.",
    content: [
      "The statistic that changed how I build CRM systems: responding to a lead within 5 minutes makes you 21x more likely to convert them than responding after 30 minutes. Yet most businesses take hours — or days — to follow up. Every one of those hours is money quietly leaking out of the business.",
      "## What speed-to-lead actually looks like",
      "Go HighLevel solves this with automation. When a lead fills a form, calls, or messages, GHL can instantly send a personalized SMS and email, notify your sales team, create an opportunity in the pipeline, and start a follow-up sequence — all in seconds, without anyone touching a keyboard. The lead gets an immediate response while your competitors are still checking their inbox.",
      "## The missed-call text-back",
      "One of my favorite builds is the missed-call text-back: when a business misses a call, the caller instantly receives a text — 'Sorry we missed you! How can we help?' — which starts a conversation that would otherwise be a lost lead. For home-service businesses that miss 30–40% of inbound calls during working hours, this single automation often pays for the whole CRM setup in the first month.",
      "Combined with an AI agent that can answer questions and book appointments, the system works 24/7. A missed call at 9pm becomes a booked estimate by 9:05pm — with zero human involvement.",
      "## Follow-up sequences that never forget",
      "The average lead needs 6–8 touches before they buy, but most salespeople give up after one or two. Automation never gives up and never forgets. I build sequences that space out SMS, email and voicemail drops over days and weeks, automatically stopping the moment the lead replies or books. Old 'dead' lead lists can be revived the same way — a database reactivation campaign to 500 old leads routinely books 10–20 new appointments.",
      "## The pipeline side matters just as much",
      "Every lead gets tracked through stages — new, contacted, booked, showed, closed — so nothing falls through the cracks and you always know exactly where your revenue is coming from. The dashboard answers questions owners usually guess at: how many leads came in this month, what percentage booked, which source brings the best customers.",
      "If your business gets leads but struggles to follow up consistently, automation isn't a luxury. It's the highest-ROI investment you can make.",
    ],
  },
  {
    slug: "ai-agents-for-business",
    title: "AI Agents: Your 24/7 Sales Assistant That Never Sleeps",
    date: "2026-04-10",
    readTime: "7 min read",
    cover: "/blog/ai.svg",
    tags: ["AI Agents", "Automation", "Lead Qualification", "Chatbots"],
    excerpt:
      "AI agents can qualify leads, answer questions, and book appointments while you sleep. Here's how I build them into real businesses.",
    content: [
      "Imagine a team member who answers every inquiry instantly, never takes a day off, qualifies every lead with the right questions, and books appointments directly into your calendar. That's what an AI agent does — and it's no longer futuristic technology, it's something I build into client systems today.",
      "## What an AI agent actually does",
      "An AI agent connected to your CRM can hold natural conversations over SMS, web chat, or social media. It answers common questions ('Do you service my area?', 'How much does it cost?'), collects the information you need — budget, timeline, service required — and when the lead is qualified, it books them into your calendar automatically. The whole exchange feels like texting with a helpful human.",
      "## The setup is everything",
      "The key to a good AI agent is the configuration: training it on your business's services, pricing logic, and tone of voice, then defining clear handoff rules so a human takes over exactly when needed — a complex question, an upset customer, a high-value deal. A poorly configured bot frustrates customers; a well-built agent feels like your best employee.",
      "I build every agent with guardrails: what it can promise, what it must never say, and when to escalate. Then we test it against dozens of real conversation scenarios before it ever talks to a customer.",
      "## Real results from real businesses",
      "For businesses in home services, real estate, healthcare, and agencies, I've seen AI agents dramatically cut response times and increase booked appointments — because the fastest responder usually wins the customer. One client's after-hours leads used to sit until morning; now the agent qualifies and books them overnight, adding 15–20 extra appointments a month.",
      "## Where to start",
      "You don't need to automate everything on day one. The best first step is a single high-leverage flow: answering new inquiries and booking calls. Once that's working, expand into FAQs, review requests and reactivation campaigns.",
      "The businesses adopting AI agents now are building a serious advantage. The question isn't whether to automate — it's how soon.",
    ],
  },
  {
    slug: "funnel-vs-website",
    title: "Funnel vs Website: Which One Does Your Business Actually Need?",
    date: "2026-03-05",
    readTime: "6 min read",
    cover: "/blog/funnel.svg",
    tags: ["Funnels", "Websites", "Conversion", "Strategy"],
    excerpt:
      "Websites build trust, funnels drive action. Most businesses need both — here's how to know what to build first.",
    content: [
      "A website is your digital headquarters: it tells your full story, builds trust, and helps people find you on Google. A funnel is a focused path with one goal — get the visitor to take a single action, like booking a call or buying a product. They look similar, but they do completely different jobs.",
      "## The mistake I see most often",
      "Running paid ads to a general website homepage. Visitors land, look around, get distracted by the menu, read the blog, and leave. A funnel fixes this by removing every distraction — one offer, one message, one button. That's why funnel pages routinely convert at 2–5x the rate of homepage traffic for the same ad spend.",
      "## When you need a funnel",
      "My rule of thumb: if you're running ads or promoting a specific offer, you need a funnel. A landing page laser-focused on the offer, a form or calendar step, and a thank-you page that sets expectations. Everything measured, so you know your exact cost per lead.",
      "## When you need a website",
      "If you want long-term organic traffic, credibility, and a home for your content, you need a website. People check you out before they buy — your website is where they decide you're legit. Service pages, portfolio, reviews, about page: they all quietly close deals in the background.",
      "## The answer for most businesses: both",
      "Most growing businesses need both, working together — the website builds authority while funnels convert campaign traffic. The best part is they share infrastructure: the same CRM, the same automation, the same tracking. Built right, every lead — whether from the website or a funnel — lands in one pipeline with automated follow-up.",
      "Start with whichever matches your next milestone: launching ads next month? Funnel first. Building a brand for the long haul? Website first — then add funnels as offers mature.",
    ],
  },
  {
    slug: "shopify-store-launch-checklist",
    title: "The Shopify Launch Checklist I Use on Every Store",
    date: "2026-07-02",
    readTime: "8 min read",
    cover: "/blog/shopify.svg",
    tags: ["Shopify", "E-commerce", "Checklist", "Conversion"],
    excerpt:
      "From payments to product pages — the exact pre-launch checklist I run on every Shopify store so it's ready to sell from day one.",
    content: [
      "Most Shopify stores don't fail because of the product — they fail because of an unfinished setup. Broken shipping rates, missing policies, product pages with one blurry photo, checkout surprises. After building stores for fashion, wellness and B2B brands, I run the same checklist on every launch. Here it is.",
      "## 1. Foundation: theme, navigation, branding",
      "Pick a fast theme and customize it to the brand — consistent colors, fonts and spacing. Navigation should take a visitor to any product within two clicks: clear collections, a working search, and a footer with policies, contact and FAQ. If the store looks assembled in a hurry, visitors assume the fulfilment is too.",
      "## 2. Product pages that actually sell",
      "Every product needs at least 4–6 photos (lifestyle plus detail shots), a description that sells the outcome, not just the specs, visible reviews, and clear shipping and return information near the buy button. This is where most conversions are won or lost — I spend more time here than anywhere else.",
      "## 3. Payments, shipping and taxes",
      "Test every payment method with a real test order — cards, wallets, and local options for your market. Set shipping zones and rates deliberately: unexpected shipping cost is the #1 reason for cart abandonment worldwide. Configure taxes for every region you sell into. Then place a complete order yourself, refund it, and make sure every email that fires along the way reads properly.",
      "## 4. The apps that earn their keep",
      "Reviews, email capture with a welcome discount, abandoned-cart recovery, and a simple upsell at checkout. That's the core stack. Every extra app slows the store down — I audit app scripts before launch and remove anything that isn't directly making money.",
      "## 5. Analytics and tracking",
      "Google Analytics 4, the Meta pixel (if you'll run ads), and Shopify's own reports wired up before the first visitor arrives. You can't improve what you don't measure — and you can't retarget visitors you never tracked.",
      "## 6. Launch-day checks",
      "Mobile walkthrough of the entire journey — most of your traffic will be on a phone. Page speed under 3 seconds. All policy pages published. Contact form tested. Favicon and social sharing image set. Then launch, watch the first orders closely, and fix the small things real customers reveal.",
      "A store set up this way doesn't just look professional — it converts from the first day, and every ad dollar you spend later works harder because the foundation is right.",
    ],
  },
  {
    slug: "wordpress-maintenance-guide",
    title: "WordPress Maintenance: Why Sites Break (And How to Keep Yours Safe)",
    date: "2026-01-18",
    readTime: "6 min read",
    cover: "/blog/maintenance.svg",
    tags: ["WordPress", "Security", "Maintenance", "Backups"],
    excerpt:
      "Hacked sites, white screens, broken layouts after an update — almost all of it is preventable. Here's the maintenance routine that keeps client sites safe.",
    content: [
      "The message usually arrives on a weekend: 'Our website is showing a white screen' or worse, 'Google says our site may be hacked.' Almost every WordPress emergency I've been called into had the same root cause — a site that hadn't been maintained in months. Outdated plugins, no backups, weak passwords, abandoned themes.",
      "## Why WordPress sites actually get hacked",
      "It's rarely a genius hacker targeting your business. It's automated bots scanning millions of sites for known vulnerabilities in outdated plugins. A plugin gets a security patch, the vulnerability becomes public, and within days bots are probing every site that hasn't updated. If your plugins are six months old, you're on that list.",
      "## The maintenance routine that prevents it",
      "Weekly: update core, themes and plugins — after a quick backup, so any conflict can be rolled back in minutes. Daily: automated off-site backups, kept for at least 30 days. Always: two-factor login, strong passwords, a firewall plugin, and removing every theme and plugin that isn't actively used. Deactivated plugins are still attack surface.",
      "## Updates without breakage",
      "The fear of 'the update broke my site' is why many owners stop updating — which makes things worse. The fix is process: backup first, update in small batches, check the key pages after each batch, and keep a staging copy for major changes like PHP version upgrades or page-builder major releases. Boring, methodical, and it works.",
      "## What a white screen really costs",
      "A day of downtime doesn't just cost that day's leads. Google notices, ad campaigns burn money sending clicks to a dead page, and customers quietly lose trust. A maintenance plan costs a fraction of a single emergency recovery — and with monitoring in place, most problems are fixed before anyone notices.",
      "If your site hasn't been updated in months, don't wait for the weekend message. A one-time cleanup plus a simple monthly routine keeps WordPress fast, safe and boring — exactly how a business website should be.",
    ],
  },
];
