export const profile = {
  name: "Shaheer Shaikh",
  firstName: "Shaheer",
  role: "WordPress Developer & GHL Expert",
  tagline:
    "WordPress and Go HighLevel (GHL) specialist with over 3 years of experience in CRM development, sales automation, and lead generation. I build responsive websites and intelligent automation workflows — including AI agent–powered systems — that help businesses convert more leads and save time.",
  phone: "03313143864",
  phoneIntl: "+923313143864",
  whatsapp: "https://wa.me/923313143864",
  email: "shaheershaikh392@gmail.com",
  location: "Karachi, Pakistan",
  cv: "/Shaheer-CV.pdf",
  website: "www.shaheershaikh392.com",
  yearsExperience: "3+",
  projectsCompleted: "500+",
};

export const socials = [
  {
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/shaheer-shaikh-ghl-expert/",
    icon: "in",
  },
  {
    name: "Instagram",
    url: "https://www.instagram.com/shaheer4436/",
    icon: "ig",
  },
  {
    name: "Facebook",
    url: "https://www.facebook.com/shaheer.shaikh.537537",
    icon: "fb",
  },
];

export const skills = [
  { name: "WordPress", level: 95, icon: "/icons/wordpress.svg" },
  { name: "GoHighLevel", level: 92, icon: "/icons/ghl.png" },
  { name: "Funnel Building", level: 90, icon: "/icons/funnel.svg" },
  { name: "AI Agents", level: 85, icon: "/icons/ai.svg" },
  { name: "Shopify", level: 80, icon: "/icons/shopify.svg" },
  { name: "HTML 5", level: 90, icon: "/icons/html5.svg" },
  { name: "CSS 3", level: 88, icon: "/icons/css.svg" },
  { name: "JavaScript", level: 75, icon: "/icons/javascript.svg" },
];

export const experience = [
  {
    company: "D1TechCreative",
    logo: "/icons/d1tech.png",
    role: "Web Developer — WordPress & GHL Expert",
    period: "Dec 2025 — Present",
    description:
      "Building and managing websites while developing CRM automations and AI agent–driven workflows to streamline client operations and lead handling.",
    tools: ["WordPress", "Elementor", "GoHighLevel", "AI Agents", "Zapier", "Funnels", "SEO"],
  },
  {
    company: "Leadflex",
    logo: "/icons/leadflex.png",
    role: "WordPress Developer & GHL Expert",
    period: "Feb 2025 — Nov 2025",
    description:
      "Built responsive websites, custom funnels, and CRM automations that boosted conversions and improved digital presence.",
    tools: ["WordPress", "GoHighLevel", "Funnel Building", "CRM Automation", "Email/SMS"],
  },
  {
    company: "Hamsol",
    logo: "/icons/hamsol.png",
    role: "WordPress Developer & GHL Expert",
    period: "Mar 2025 — Dec 2025",
    description:
      "Built responsive, SEO-optimized websites with custom themes. Focused on improving speed, design, and functionality using HTML, CSS, PHP, and WordPress customization.",
    tools: ["WordPress", "HTML5", "CSS3", "PHP", "Speed Optimization", "SEO"],
  },
  {
    company: "Zg Tech Solutions",
    logo: "/icons/zgtech.png",
    role: "WordPress Developer & GHL Expert",
    period: "Feb 2023 — Dec 2024",
    description:
      "Developed websites, custom funnels, and CRM automations that improved lead generation for clients.",
    tools: ["WordPress", "Elementor", "GoHighLevel", "Lead Generation", "JavaScript"],
  },
];

export const achievements = [
  {
    title: "500+ Websites Launched",
    period: "2023 — Present",
    description:
      "Designed, built and launched over five hundred websites across WordPress, Shopify and GoHighLevel for clients in the US, UK, Australia, UAE and Pakistan.",
  },
  {
    title: "40+ GoHighLevel Funnels & CRM Systems",
    period: "2024 — Present",
    description:
      "Delivered complete GHL builds — pipelines, calendars, automations and AI agents — for agencies, real estate teams, healthcare and home-service businesses.",
  },
  {
    title: "Sub-2-Second Load Times",
    period: "Ongoing",
    description:
      "Speed-optimized dozens of WordPress sites from 4–8 second loads down to under 2 seconds, passing Core Web Vitals and improving search rankings.",
  },
  {
    title: "AI Agent Systems in Production",
    period: "2025 — Present",
    description:
      "Built AI-powered conversation agents that qualify leads, answer FAQs and book appointments 24/7 — running live inside client CRMs.",
  },
];

export const education = [
  {
    school: "Federal Urdu University of Karachi",
    logo: "/icons/fuuast.png",
    degree: "Bachelor of Science in Computer Information",
    period: "2025 — 2029 · Present",
  },
  {
    school: "Aptech",
    logo: "/icons/aptech.png",
    degree: "ACCP Prime 2.0",
    period: "2022 — 2025 · Completed",
  },
  {
    school: "Government Polytechnic Institute",
    logo: "/icons/gpi.png",
    degree: "Diploma of Associate Engineering (3 Years)",
    period: "2022 — 2025 · Completed",
  },
  {
    school: "Al Jawad Higher Secondary School",
    degree: "Intermediate",
    period: "2022 — 2024",
  },
  {
    school: "Wali Memorial Public School",
    degree: "Matriculation",
    period: "2010 — 2022",
  },
];

export const services = [
  {
    slug: "wordpress-development",
    title: "WordPress Development",
    short: "Fast, responsive, SEO-ready WordPress websites with custom themes.",
    description:
      "I design and develop custom WordPress websites that load fast, rank well, and convert visitors into customers. From landing pages to full business sites — custom themes, plugin configuration, speed optimization, and on-page SEO are all part of the package.",
    points: [
      "Custom theme design & development",
      "Speed & Core Web Vitals optimization",
      "SEO-friendly structure",
      "Responsive on every device",
      "Elementor / page-builder expertise",
    ],
  },
  {
    slug: "ghl-crm-automation",
    title: "GHL CRM & Automation",
    short: "Go HighLevel CRM setup, pipelines and sales automation that never sleeps.",
    description:
      "As a Go HighLevel expert, I build complete CRM systems: pipelines, calendars, SMS/email follow-up sequences, and automations that capture, nurture, and convert leads on autopilot — so your team can focus on closing.",
    points: [
      "Full GHL account setup & snapshots",
      "Sales pipelines & opportunity tracking",
      "Automated SMS / email follow-ups",
      "Appointment booking & reminders",
      "Reporting dashboards",
    ],
  },
  {
    slug: "funnel-building",
    title: "Funnel Building & Optimization",
    short: "High-converting sales funnels engineered to turn clicks into customers.",
    description:
      "I build and optimize sales funnels — landing pages, upsells, order forms, and thank-you flows — with tracking wired in, then iterate on copy and layout to increase conversion rates.",
    points: [
      "Landing page design",
      "A/B-ready funnel structures",
      "Upsell / downsell flows",
      "Conversion tracking & pixels",
      "Copy & layout optimization",
    ],
  },
  {
    slug: "ai-agents-workflows",
    title: "AI Agents & Workflows",
    short: "AI agent–powered systems that qualify leads and reply 24/7.",
    description:
      "I develop intelligent automation workflows powered by AI agents — conversation bots that qualify leads, book appointments, and answer FAQs around the clock, integrated directly into your CRM.",
    points: [
      "AI conversation bots for lead qualification",
      "24/7 automated responses",
      "Appointment-booking agents",
      "CRM-integrated workflows",
      "Custom automation logic",
    ],
  },
  {
    slug: "shopify",
    title: "Shopify Store Setup",
    short: "Clean, conversion-focused Shopify stores ready to sell.",
    description:
      "From theme customization to product setup, payments and apps — I build Shopify stores that look professional and are optimized to sell from day one.",
    points: [
      "Theme setup & customization",
      "Product & collection setup",
      "Payments & shipping configuration",
      "App integration",
      "Conversion-focused layout",
    ],
  },
  {
    slug: "lead-generation",
    title: "Lead Generation Systems",
    short: "End-to-end systems that capture, nurture and convert leads.",
    description:
      "Website + funnel + CRM + automation, working together as one machine. I connect every piece so no lead falls through the cracks — capture forms, instant follow-up, nurturing sequences, and clear reporting.",
    points: [
      "Lead capture forms & pop-ups",
      "Instant speed-to-lead follow-up",
      "Nurture sequences",
      "Pipeline visibility",
      "ROI reporting",
    ],
  },
];

export const pricing = [
  {
    platform: "WordPress",
    icon: "/icons/wordpress.svg",
    tagline:
      "Business websites, service sites and blogs — fast, SEO-ready and easy to manage.",
    plans: [
      {
        name: "Starter",
        price: 150,
        priceNote: "one-time",
        pages: "Up to 5 pages",
        summary:
          "Perfect for small businesses that need a clean, professional online presence.",
        features: [
          "Home, About, Services, Contact + 1 page",
          "Mobile-responsive design",
          "Contact form with email notifications",
          "Basic on-page SEO setup",
          "Google Maps & social links",
          "Speed-optimized setup",
        ],
        delivery: "5–7 days delivery",
      },
      {
        name: "Business",
        price: 300,
        priceNote: "one-time",
        pages: "Up to 10 pages",
        popular: true,
        summary:
          "The complete package for service businesses — like the sites in my portfolio.",
        features: [
          "Custom design (Elementor / custom theme)",
          "Service pages + blog setup",
          "Lead capture forms & pop-ups",
          "Speed & Core Web Vitals optimization",
          "On-page SEO for every page",
          "WhatsApp / live chat integration",
          "Google Analytics & Search Console",
        ],
        delivery: "7–14 days delivery",
      },
      {
        name: "Premium / WooCommerce",
        price: 600,
        priceNote: "starting at",
        pages: "15+ pages or full store",
        summary:
          "Large business sites or full online stores with WooCommerce.",
        features: [
          "Everything in Business",
          "WooCommerce store setup",
          "Up to 50 products added",
          "Payment gateway & shipping setup",
          "Advanced speed optimization",
          "Admin training video",
          "30 days post-launch support",
        ],
        delivery: "2–3 weeks delivery",
      },
    ],
  },
  {
    platform: "Shopify",
    icon: "/icons/shopify.svg",
    tagline:
      "Conversion-focused Shopify stores — set up properly and ready to sell from day one.",
    plans: [
      {
        name: "Basic Store",
        price: 250,
        priceNote: "one-time",
        pages: "Core store pages",
        summary:
          "A clean store on a free theme — ideal for launching your first products.",
        features: [
          "Theme setup & branding",
          "Up to 10 products added",
          "Home, About, Contact & policy pages",
          "Payment & shipping configuration",
          "Basic navigation & collections",
          "Mobile-ready checkout",
        ],
        delivery: "4–6 days delivery",
      },
      {
        name: "Standard Store",
        price: 450,
        priceNote: "one-time",
        pages: "Full store + custom sections",
        popular: true,
        summary:
          "Customized design and everything configured — the way stores like Milli Collections were built.",
        features: [
          "Premium theme customization",
          "Up to 50 products with collections",
          "Custom homepage sections",
          "Essential apps (reviews, upsell, email pop-up)",
          "Discount & shipping rules",
          "Basic email automation (abandoned cart)",
          "On-page SEO for products",
        ],
        delivery: "1–2 weeks delivery",
      },
      {
        name: "Premium Store",
        price: 800,
        priceNote: "starting at",
        pages: "Fully custom store",
        summary:
          "A fully custom, conversion-optimized store for serious brands.",
        features: [
          "Everything in Standard",
          "Custom design & landing pages",
          "Up to 200 products migrated/added",
          "Conversion rate optimization",
          "Advanced app stack & integrations",
          "Store training video",
          "30 days post-launch support",
        ],
        delivery: "2–3 weeks delivery",
      },
    ],
  },
  {
    platform: "GoHighLevel",
    icon: "/icons/ghl.png",
    tagline:
      "Websites, funnels and CRM automation inside GHL — built to capture and convert leads 24/7.",
    plans: [
      {
        name: "Funnel Build",
        price: 200,
        priceNote: "one-time",
        pages: "1 funnel · up to 3 steps",
        summary:
          "A high-converting funnel for your offer — landing page, form and thank-you flow.",
        features: [
          "Landing page + thank-you page",
          "Opt-in form or survey",
          "Email & SMS confirmation automation",
          "Calendar booking step (optional)",
          "Tracking pixels installed",
          "Mobile-optimized design",
        ],
        delivery: "3–5 days delivery",
      },
      {
        name: "Website + CRM Setup",
        price: 450,
        priceNote: "one-time",
        pages: "Up to 8 pages + CRM",
        popular: true,
        summary:
          "Full GHL website with pipelines and follow-up automation — my most-requested build.",
        features: [
          "Complete GHL website (up to 8 pages)",
          "Sales pipeline & opportunity stages",
          "Calendar & appointment booking",
          "Automated email/SMS follow-ups",
          "Missed-call text-back automation",
          "Lead forms wired into the CRM",
          "Reporting dashboard setup",
        ],
        delivery: "1–2 weeks delivery",
      },
      {
        name: "Complete Automation Suite",
        price: 900,
        priceNote: "starting at",
        pages: "Website + funnels + AI",
        summary:
          "The full machine: website, funnels, CRM and an AI agent working around the clock.",
        features: [
          "Everything in Website + CRM",
          "Sales funnel(s) for your offers",
          "AI agent for chat & lead qualification",
          "Advanced multi-step workflows",
          "Snapshot of the whole system",
          "Third-party integrations (Zapier etc.)",
          "30 days post-launch support",
        ],
        delivery: "2–4 weeks delivery",
      },
    ],
  },
];

export const projects = [
  {
    name: "D1 Tech Creative",
    url: "https://www.d1techcreative.com/",
    image: "/shots/d1techcreative.webp",
    category: "Agency",
    platform: "WordPress",
    description: "Digital agency website with modern design and lead-gen focus.",
  },
  {
    name: "The Clean Power Experts",
    url: "https://thecleanpowerexperts.com/",
    image: "/shots/thecleanpowerexperts.webp",
    category: "Solar / Energy",
    platform: "WordPress",
    description: "Solar energy company site built to capture and convert leads.",
  },
  {
    name: "GuaraBoost",
    url: "https://guaraboost.com/",
    image: "/shots/guaraboost.webp",
    category: "E-commerce",
    platform: "WordPress",
    description: "Product brand website with bold visuals and online sales flow.",
  },
  {
    name: "A Plus Moving & Storage",
    url: "https://aplusmovingandstorage.co/",
    image: "/shots/aplusmovingandstorage.webp",
    category: "Services",
    platform: "WordPress",
    description: "Moving company site with quote funnels and service pages.",
  },
  {
    name: "The Paper Roll",
    url: "https://thepaperroll.com/",
    image: "/shots/thepaperroll.webp",
    category: "E-commerce",
    platform: "WordPress",
    description: "B2B paper products store with catalog and ordering.",
  },
  {
    name: "Done By Dorfman",
    url: "https://www.donebydorfman.com",
    image: "/shots/donebydorfman.webp",
    category: "Personal Brand",
    platform: "WordPress",
    description: "Personal brand website with clean, professional presentation.",
  },
  {
    name: "Hamza Shakeel",
    url: "https://hamzashakeel.com/",
    image: "/shots/hamzashakeel.webp",
    category: "Personal Brand",
    platform: "WordPress",
    description: "Portfolio and personal brand site for a professional.",
  },
  {
    name: "Engr Sehtesham Hussain",
    url: "https://engrsehteshamhussain.com/",
    image: "/shots/engrsehteshamhussain.webp",
    category: "Personal Brand",
    platform: "WordPress",
    description: "Professional engineer's personal website and portfolio.",
  },
  {
    name: "Qulfi Wala",
    url: "https://qulfiwala.com/",
    image: "/shots/qulfiwala.webp",
    category: "Food Brand",
    platform: "WordPress",
    description: "Dessert brand website with menu and brand storytelling.",
  },
  {
    name: "Simplee Digital",
    url: "https://simplee.digital/",
    image: "/shots/simplee.webp",
    category: "Agency",
    platform: "WordPress",
    description: "Digital marketing agency site with service funnels.",
  },
  {
    name: "Everest Equipment Finance",
    url: "https://everestequipmentfinance.com/",
    image: "/shots/everestequipmentfinance.webp",
    category: "Finance",
    platform: "WordPress",
    description: "Equipment financing company with application funnels.",
  },
  {
    name: "Morse Junk Removal",
    url: "https://morsejunk.com/",
    image: "/shots/morsejunk.webp",
    category: "Services",
    platform: "WordPress",
    description: "Junk removal service site with booking and quote flows.",
  },
  {
    name: "Kyan Trading Services",
    url: "https://kyantradingservices.com/",
    image: "/shots/kyantradingservices.webp",
    category: "Trading",
    platform: "WordPress",
    description: "Trading and services company with corporate design.",
  },
  {
    name: "VitaHub",
    url: "https://vitahub.pk/",
    image: "/shots/vitahub.webp",
    category: "E-commerce",
    platform: "WordPress",
    description: "Health & wellness e-commerce store for Pakistan.",
  },
  {
    name: "Mary Angels Home Care",
    url: "https://www.maryangelshomecare.com/",
    image: "/shots/maryangelshomecare.webp",
    category: "Healthcare",
    platform: "WordPress",
    description: "Home care services website with warm, trustworthy design.",
  },
  {
    name: "Aligned Chiro",
    url: "https://alignedchiro.com.au/",
    image: "/shots/alignedchiro.webp",
    category: "Healthcare",
    platform: "Shopify",
    description: "Australian chiropractic clinic store built on Shopify.",
  },
  {
    name: "Milli Collections",
    url: "https://millicollections.com/",
    image: "/shots/millicollections.webp",
    category: "E-commerce",
    platform: "Shopify",
    description: "Fashion & lifestyle Shopify store with clean product showcase.",
  },
  {
    name: "Compelified",
    url: "https://www.compelified.com/",
    image: "/shots/compelified.webp",
    category: "E-commerce",
    platform: "Shopify",
    description: "Modern Shopify store with conversion-focused product pages.",
  },
  {
    name: "GHL Rockstar",
    url: "https://ghlrockstar.com/",
    image: "/shots/ghlrockstar.webp",
    category: "Agency",
    platform: "GoHighLevel",
    description: "GoHighLevel agency website with funnels and automation.",
  },
  {
    name: "Foreclosure Solutions USA",
    url: "https://foreclosuresolutionsusa.com/",
    image: "/shots/foreclosuresolutionsusa.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Real estate foreclosure help site with lead capture funnels.",
  },
  {
    name: "Liv Funding",
    url: "https://livfunding.com/",
    image: "/shots/livfunding.webp",
    category: "Finance",
    platform: "GoHighLevel",
    description: "Business funding website with application funnels.",
  },
  {
    name: "Soul Software",
    url: "https://soulsoftware.co/",
    image: "/shots/soulsoftware.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "Software company site built on GoHighLevel.",
  },
  {
    name: "Lewicki Team",
    url: "https://lewickiteam.com/",
    image: "/shots/lewickiteam.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Real estate team website with lead generation setup.",
  },
  {
    name: "Vanity Van Lines",
    url: "https://vanityvanlines.com/",
    image: "/shots/vanityvanlines.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Moving company website with quote request funnels.",
  },
  {
    name: "PW Hospital",
    url: "https://pwhospital.org/",
    image: "/shots/pwhospital.webp",
    category: "Healthcare",
    platform: "GoHighLevel",
    description: "Hospital website with appointment booking flows.",
  },
  {
    name: "Where2Print",
    url: "https://where2print.com/",
    image: "/shots/where2print.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Printing services website with order funnels.",
  },
  {
    name: "Top Local House Buyers",
    url: "https://toplocalhousebuyers.com/",
    image: "/shots/toplocalhousebuyers.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Cash home buying site with seller lead funnels.",
  },
  {
    name: "iPrograms",
    url: "https://iprograms.com/",
    image: "/shots/iprograms.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "Programs and software platform website.",
  },
  {
    name: "Impress Tech",
    url: "https://impresstech.com/",
    image: "/shots/impresstech.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "Technology company website built on GoHighLevel.",
  },
  {
    name: "Paw Works",
    url: "https://pawworks.org/",
    image: "/shots/pawworks.webp",
    category: "Nonprofit",
    platform: "GoHighLevel",
    description: "Animal rescue nonprofit website with donation flows.",
  },
  {
    name: "Valor House Buyers",
    url: "https://valorhousebuyers.com/",
    image: "/shots/valorhousebuyers.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Home buying company site with lead capture.",
  },
  {
    name: "Julie's Home Cleaning",
    url: "https://julieshomecleaning.com/",
    image: "/shots/julieshomecleaning.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Home cleaning services website with booking funnels.",
  },
  {
    name: "Immigration Law Firm",
    url: "https://app.gohighlevel.com/v2/preview/9VZiRF4mB7IYd5tt3F8I",
    image: "/shots/ghlpreview01.webp",
    category: "Legal",
    platform: "GoHighLevel",
    description: "Immigration & family law firm site with consultation booking.",
  },
  {
    name: "Philadelphia Basketball School",
    url: "https://app.gohighlevel.com/v2/preview/gXJSlzbBWKVgNbhROvOe",
    image: "/shots/ghlpreview02.webp",
    category: "Sports",
    platform: "GoHighLevel",
    description: "Youth sports program website with signup funnels.",
  },
  {
    name: "AW Loans",
    url: "https://app.gohighlevel.com/v2/preview/e5Be3MSbYxiPClLshP5p",
    image: "/shots/ghlpreview03.webp",
    category: "Finance",
    platform: "GoHighLevel",
    description: "Mortgage solutions website with quote request flows.",
  },
  {
    name: "HUBU Accountants",
    url: "https://app.gohighlevel.com/v2/preview/mEqt9FqyMcZLsKXxqXiF",
    image: "/shots/ghlpreview04.webp",
    category: "Finance",
    platform: "GoHighLevel",
    description: "Accounting firm site — taxation, bookkeeping and VAT services.",
  },
  {
    name: "VoiceAI HQ",
    url: "https://app.gohighlevel.com/v2/preview/YOuhR1vFnVCID3vC4AwN",
    image: "/shots/ghlpreview05.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "AI receptionist product site with demo and trial funnels.",
  },
  {
    name: "Clover Assist",
    url: "https://app.gohighlevel.com/v2/preview/NZQWwDRnoe5TQpWrak4M",
    image: "/shots/ghlpreview06.webp",
    category: "Technology",
    platform: "GoHighLevel",
    description: "AI employee platform site that books meetings and closes leads.",
  },
  {
    name: "Sobha Hartland Apartments",
    url: "https://app.gohighlevel.com/v2/preview/7qdFoQ9lysbXF4BQ3Jyy",
    image: "/shots/ghlpreview07.webp",
    category: "Real Estate",
    platform: "GoHighLevel",
    description: "Dubai luxury apartments funnel with WhatsApp lead capture.",
  },
  {
    name: "FitPro PlayBook",
    url: "https://app.gohighlevel.com/v2/preview/xjasAdmNVUlGfJxeLRDP",
    image: "/shots/ghlpreview08.webp",
    category: "Coaching",
    platform: "GoHighLevel",
    description: "Fitness business coaching site with mentorship funnels.",
  },
  {
    name: "Lawnella Landscaping",
    url: "https://app.gohighlevel.com/v2/preview/gXxYJubnWi0QzwsSrWXc",
    image: "/shots/ghlpreview09.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Landscaping company site with residential & commercial services.",
  },
  {
    name: "Tube Mastery",
    url: "https://app.gohighlevel.com/v2/preview/Dqzrkrq119CHWXnqmvdj",
    image: "/shots/ghlpreview10.webp",
    category: "Coaching",
    platform: "GoHighLevel",
    description: "YouTube monetization course funnel with community signup.",
  },
  {
    name: "KillShot Auto Detailing",
    url: "https://app.gohighlevel.com/v2/preview/CzQenp1VcYGUwQujlSbZ",
    image: "/shots/ghlpreview11.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Luxury car detailing site with service tiers and booking.",
  },
  {
    name: "EdBridge",
    url: "https://app.gohighlevel.com/v2/preview/NShlaDO5vuPDqhJvRzFO",
    image: "/shots/ghlpreview12.webp",
    category: "Education",
    platform: "GoHighLevel",
    description: "Education platform site for in-demand digital skills.",
  },
  {
    name: "TradeAid",
    url: "https://app.gohighlevel.com/v2/preview/L89S1rj6jyKsYDgjuh1c",
    image: "/shots/ghlpreview13.webp",
    category: "Services",
    platform: "GoHighLevel",
    description: "Construction professionals community with WhatsApp onboarding.",
  },
  {
    name: "Aligned Chiro Funnel",
    url: "https://app.gohighlevel.com/v2/preview/VOpquZUpoh0mxLAWhS0l?notrack=true",
    image: "/shots/ghlpreview14.webp",
    category: "Healthcare",
    platform: "GoHighLevel",
    description: "Chiropractic consultation offer funnel with pain assessment.",
  },
];

export const testimonials = [
  {
    name: "Daniel R.",
    role: "Founder — D1 Tech Creative",
    text: "Shaheer is our go-to developer for WordPress and GHL. Fast, reliable, and he genuinely cares about conversions — every site he touches performs better.",
  },
  {
    name: "Michael T.",
    role: "The Clean Power Experts",
    text: "Our solar site went from slow and clunky to fast and lead-generating. The forms, the funnels, the follow-up automation — everything just works.",
  },
  {
    name: "Gavin M.",
    role: "Morse Hauling & Junk Removal",
    text: "The new website brings us real calls every week. Free estimate form, reviews, service areas — Shaheer set the whole machine up perfectly.",
  },
  {
    name: "Sarah K.",
    role: "Mary Angels Home Care",
    text: "Professional, patient and quick. He understood exactly the warm, trustworthy feel we needed for our home care brand.",
  },
  {
    name: "Imran M.",
    role: "Qulfi Wala",
    text: "Hamari brand website ne business hi badal diya. Design bhi zabardast, speed bhi — aur order flow bilkul asaan.",
  },
  {
    name: "Ali H.",
    role: "VitaHub Pakistan",
    text: "From product pages to checkout, the store is clean and fast. Sales improved within the first month of launch.",
  },
  {
    name: "James L.",
    role: "Everest Equipment Finance",
    text: "The application funnels Shaheer built qualify leads before they ever reach our team. Massive time saver.",
  },
  {
    name: "Hamza S.",
    role: "hamzashakeel.com",
    text: "My personal brand site looks world-class. Smooth animations, quick load, and it actually gets me client inquiries.",
  },
];

export const blogPosts = [
  {
    slug: "why-website-speed-matters",
    title: "Why Website Speed Matters (And How I Make WordPress Fly)",
    date: "2026-06-15",
    readTime: "7 min read",
    cover: "/blog/speed.svg",
    tags: ["WordPress", "Speed", "Core Web Vitals", "SEO"],
    excerpt:
      "A slow website silently kills your conversions. Here's the exact process I use to make WordPress sites load in under 2 seconds.",
    content: [
      "Every extra second your website takes to load, you lose visitors — studies consistently show that bounce rates jump dramatically after the 3-second mark. Google's own research found that as page load time goes from 1 second to 3 seconds, the probability of a bounce increases by 32%. At 5 seconds, it jumps to 90%. For a business website, speed isn't a technical detail. It's revenue.",
      "## The real cost of a slow website",
      "Imagine 1,000 people visit your site this month from ads, Google and social media. If your site takes 6 seconds to load, roughly half of them leave before seeing anything. That's 500 potential customers gone — not because your offer was bad, but because a spinner was still turning. I've seen service businesses double their lead volume without changing a single word of copy, purely by fixing load time.",
      "## Where WordPress sites lose their speed",
      "When I take on a speed project, I start with a full audit: which plugins load scripts on every page, how large the images are, whether the hosting is up to the job, and what the Core Web Vitals report says. Most slow sites share the same three problems — bloated page builders loading 2MB of JavaScript, unoptimized 4000-pixel images uploaded straight from a phone, and no caching strategy at all.",
      "The plugin problem is the sneakiest. A site accumulates plugins over the years — a slider here, a form there, three different SEO tools — and each one adds its own CSS and JavaScript to every single page. Twenty active plugins can easily mean sixty extra HTTP requests before your content even appears.",
      "## My optimization process",
      "My process covers image compression and WebP conversion, lazy loading below the fold, full-page caching plus browser and object cache, removing unused CSS and JavaScript per page, database cleanup, and choosing lightweight alternatives to heavy plugins. Where the hosting is the bottleneck, I move clients to servers with LiteSpeed or NGINX and PHP 8+. On most projects this takes a site from a 4–8 second load down to under 2 seconds.",
      "I always measure before and after with the same tools — PageSpeed Insights, GTmetrix and real-device testing on 4G — so the improvement is documented, not just 'it feels faster'.",
      "## What you get from a fast site",
      "The result isn't just a better PageSpeed score. Faster sites rank higher on Google (Core Web Vitals are a confirmed ranking signal), convert better, and feel more trustworthy to visitors. If your site feels slow, it's costing you leads every single day — and it's almost always fixable within a week.",
    ],
  },
  {
    slug: "ghl-automation-guide",
    title: "How GHL Automation Turns Missed Calls Into Booked Appointments",
    date: "2026-05-20",
    readTime: "8 min read",
    cover: "/blog/ghl.svg",
    tags: ["GoHighLevel", "Automation", "CRM", "Speed-to-Lead"],
    excerpt:
      "Speed-to-lead is everything. Here's how I build Go HighLevel automations that respond to every lead in under 60 seconds.",
    content: [
      "The statistic that changed how I build CRM systems: responding to a lead within 5 minutes makes you 21x more likely to convert them than responding after 30 minutes. Yet most businesses take hours — or days — to follow up. Every one of those hours is money quietly leaking out of the business.",
      "## What speed-to-lead actually looks like",
      "Go HighLevel solves this with automation. When a lead fills a form, calls, or messages, GHL can instantly send a personalized SMS and email, notify your sales team, create an opportunity in the pipeline, and start a follow-up sequence — all in seconds, without anyone touching a keyboard. The lead gets an immediate response while your competitors are still checking their inbox.",
      "## The missed-call text-back",
      "One of my favorite builds is the missed-call text-back: when a business misses a call, the caller instantly receives a text — 'Sorry we missed you! How can we help?' — which starts a conversation that would otherwise be a lost lead. For home-service businesses that miss 30–40% of inbound calls during working hours, this single automation often pays for the whole CRM setup in the first month.",
      "Combined with an AI agent that can answer questions and book appointments, the system works 24/7. A missed call at 9pm becomes a booked estimate by 9:05pm — with zero human involvement.",
      "## Follow-up sequences that never forget",
      "The average lead needs 6–8 touches before they buy, but most salespeople give up after one or two. Automation never gives up and never forgets. I build sequences that space out SMS, email and voicemail drops over days and weeks, automatically stopping the moment the lead replies or books. Old 'dead' lead lists can be revived the same way — a database reactivation campaign to 500 old leads routinely books 10–20 new appointments.",
      "## The pipeline side matters just as much",
      "Every lead gets tracked through stages — new, contacted, booked, showed, closed — so nothing falls through the cracks and you always know exactly where your revenue is coming from. The dashboard answers questions owners usually guess at: how many leads came in this month, what percentage booked, which source brings the best customers.",
      "If your business gets leads but struggles to follow up consistently, automation isn't a luxury. It's the highest-ROI investment you can make.",
    ],
  },
  {
    slug: "ai-agents-for-business",
    title: "AI Agents: Your 24/7 Sales Assistant That Never Sleeps",
    date: "2026-04-10",
    readTime: "7 min read",
    cover: "/blog/ai.svg",
    tags: ["AI Agents", "Automation", "Lead Qualification", "Chatbots"],
    excerpt:
      "AI agents can qualify leads, answer questions, and book appointments while you sleep. Here's how I build them into real businesses.",
    content: [
      "Imagine a team member who answers every inquiry instantly, never takes a day off, qualifies every lead with the right questions, and books appointments directly into your calendar. That's what an AI agent does — and it's no longer futuristic technology, it's something I build into client systems today.",
      "## What an AI agent actually does",
      "An AI agent connected to your CRM can hold natural conversations over SMS, web chat, or social media. It answers common questions ('Do you service my area?', 'How much does it cost?'), collects the information you need — budget, timeline, service required — and when the lead is qualified, it books them into your calendar automatically. The whole exchange feels like texting with a helpful human.",
      "## The setup is everything",
      "The key to a good AI agent is the configuration: training it on your business's services, pricing logic, and tone of voice, then defining clear handoff rules so a human takes over exactly when needed — a complex question, an upset customer, a high-value deal. A poorly configured bot frustrates customers; a well-built agent feels like your best employee.",
      "I build every agent with guardrails: what it can promise, what it must never say, and when to escalate. Then we test it against dozens of real conversation scenarios before it ever talks to a customer.",
      "## Real results from real businesses",
      "For businesses in home services, real estate, healthcare, and agencies, I've seen AI agents dramatically cut response times and increase booked appointments — because the fastest responder usually wins the customer. One client's after-hours leads used to sit until morning; now the agent qualifies and books them overnight, adding 15–20 extra appointments a month.",
      "## Where to start",
      "You don't need to automate everything on day one. The best first step is a single high-leverage flow: answering new inquiries and booking calls. Once that's working, expand into FAQs, review requests and reactivation campaigns.",
      "The businesses adopting AI agents now are building a serious advantage. The question isn't whether to automate — it's how soon.",
    ],
  },
  {
    slug: "funnel-vs-website",
    title: "Funnel vs Website: Which One Does Your Business Actually Need?",
    date: "2026-03-05",
    readTime: "6 min read",
    cover: "/blog/funnel.svg",
    tags: ["Funnels", "Websites", "Conversion", "Strategy"],
    excerpt:
      "Websites build trust, funnels drive action. Most businesses need both — here's how to know what to build first.",
    content: [
      "A website is your digital headquarters: it tells your full story, builds trust, and helps people find you on Google. A funnel is a focused path with one goal — get the visitor to take a single action, like booking a call or buying a product. They look similar, but they do completely different jobs.",
      "## The mistake I see most often",
      "Running paid ads to a general website homepage. Visitors land, look around, get distracted by the menu, read the blog, and leave. A funnel fixes this by removing every distraction — one offer, one message, one button. That's why funnel pages routinely convert at 2–5x the rate of homepage traffic for the same ad spend.",
      "## When you need a funnel",
      "My rule of thumb: if you're running ads or promoting a specific offer, you need a funnel. A landing page laser-focused on the offer, a form or calendar step, and a thank-you page that sets expectations. Everything measured, so you know your exact cost per lead.",
      "## When you need a website",
      "If you want long-term organic traffic, credibility, and a home for your content, you need a website. People check you out before they buy — your website is where they decide you're legit. Service pages, portfolio, reviews, about page: they all quietly close deals in the background.",
      "## The answer for most businesses: both",
      "Most growing businesses need both, working together — the website builds authority while funnels convert campaign traffic. The best part is they share infrastructure: the same CRM, the same automation, the same tracking. Built right, every lead — whether from the website or a funnel — lands in one pipeline with automated follow-up.",
      "Start with whichever matches your next milestone: launching ads next month? Funnel first. Building a brand for the long haul? Website first — then add funnels as offers mature.",
    ],
  },
  {
    slug: "shopify-store-launch-checklist",
    title: "The Shopify Launch Checklist I Use on Every Store",
    date: "2026-07-02",
    readTime: "8 min read",
    cover: "/blog/shopify.svg",
    tags: ["Shopify", "E-commerce", "Checklist", "Conversion"],
    excerpt:
      "From payments to product pages — the exact pre-launch checklist I run on every Shopify store so it's ready to sell from day one.",
    content: [
      "Most Shopify stores don't fail because of the product — they fail because of an unfinished setup. Broken shipping rates, missing policies, product pages with one blurry photo, checkout surprises. After building stores for fashion, wellness and B2B brands, I run the same checklist on every launch. Here it is.",
      "## 1. Foundation: theme, navigation, branding",
      "Pick a fast theme and customize it to the brand — consistent colors, fonts and spacing. Navigation should take a visitor to any product within two clicks: clear collections, a working search, and a footer with policies, contact and FAQ. If the store looks assembled in a hurry, visitors assume the fulfilment is too.",
      "## 2. Product pages that actually sell",
      "Every product needs at least 4–6 photos (lifestyle plus detail shots), a description that sells the outcome, not just the specs, visible reviews, and clear shipping and return information near the buy button. This is where most conversions are won or lost — I spend more time here than anywhere else.",
      "## 3. Payments, shipping and taxes",
      "Test every payment method with a real test order — cards, wallets, and local options for your market. Set shipping zones and rates deliberately: unexpected shipping cost is the #1 reason for cart abandonment worldwide. Configure taxes for every region you sell into. Then place a complete order yourself, refund it, and make sure every email that fires along the way reads properly.",
      "## 4. The apps that earn their keep",
      "Reviews, email capture with a welcome discount, abandoned-cart recovery, and a simple upsell at checkout. That's the core stack. Every extra app slows the store down — I audit app scripts before launch and remove anything that isn't directly making money.",
      "## 5. Analytics and tracking",
      "Google Analytics 4, the Meta pixel (if you'll run ads), and Shopify's own reports wired up before the first visitor arrives. You can't improve what you don't measure — and you can't retarget visitors you never tracked.",
      "## 6. Launch-day checks",
      "Mobile walkthrough of the entire journey — most of your traffic will be on a phone. Page speed under 3 seconds. All policy pages published. Contact form tested. Favicon and social sharing image set. Then launch, watch the first orders closely, and fix the small things real customers reveal.",
      "A store set up this way doesn't just look professional — it converts from the first day, and every ad dollar you spend later works harder because the foundation is right.",
    ],
  },
  {
    slug: "wordpress-maintenance-guide",
    title: "WordPress Maintenance: Why Sites Break (And How to Keep Yours Safe)",
    date: "2026-01-18",
    readTime: "6 min read",
    cover: "/blog/maintenance.svg",
    tags: ["WordPress", "Security", "Maintenance", "Backups"],
    excerpt:
      "Hacked sites, white screens, broken layouts after an update — almost all of it is preventable. Here's the maintenance routine that keeps client sites safe.",
    content: [
      "The message usually arrives on a weekend: 'Our website is showing a white screen' or worse, 'Google says our site may be hacked.' Almost every WordPress emergency I've been called into had the same root cause — a site that hadn't been maintained in months. Outdated plugins, no backups, weak passwords, abandoned themes.",
      "## Why WordPress sites actually get hacked",
      "It's rarely a genius hacker targeting your business. It's automated bots scanning millions of sites for known vulnerabilities in outdated plugins. A plugin gets a security patch, the vulnerability becomes public, and within days bots are probing every site that hasn't updated. If your plugins are six months old, you're on that list.",
      "## The maintenance routine that prevents it",
      "Weekly: update core, themes and plugins — after a quick backup, so any conflict can be rolled back in minutes. Daily: automated off-site backups, kept for at least 30 days. Always: two-factor login, strong passwords, a firewall plugin, and removing every theme and plugin that isn't actively used. Deactivated plugins are still attack surface.",
      "## Updates without breakage",
      "The fear of 'the update broke my site' is why many owners stop updating — which makes things worse. The fix is process: backup first, update in small batches, check the key pages after each batch, and keep a staging copy for major changes like PHP version upgrades or page-builder major releases. Boring, methodical, and it works.",
      "## What a white screen really costs",
      "A day of downtime doesn't just cost that day's leads. Google notices, ad campaigns burn money sending clicks to a dead page, and customers quietly lose trust. A maintenance plan costs a fraction of a single emergency recovery — and with monitoring in place, most problems are fixed before anyone notices.",
      "If your site hasn't been updated in months, don't wait for the weekend message. A one-time cleanup plus a simple monthly routine keeps WordPress fast, safe and boring — exactly how a business website should be.",
    ],
  },
];
